server:
  port: 8080
spring:
  # cloud:
  #   gateway:
  #     routes:
  #       - id: user-service
  #         uri: http://<SERVICE_EC2_PRIVATE_IP>:9000
  #         predicates: [ Path=/users/** ]
  #       - id: routine-service
  #         uri: http://<SERVICE_EC2_PRIVATE_IP>:9000
  #         predicates: [ Path=/routines/** ]
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            http2:
              enabled: false   # ← h2c 금지 (HTTP/1.1 사용)
            pool:
              max-connections: 1000
          routes:
            - id: user-service
              uri: http://nginx-cache:9000
              predicates:
                - Path=/users,/users/**
              filters:
                - StripPrefix=0
            - id: routine-service
              uri: http://nginx-cache:9000
              predicates:
                - Path=/routines,/routines/**
              filters:
                - StripPrefix=0
eureka:
  client:
    service-url:
      #defaultZone: http://<EUREKA_PRIVATE_IP>:8761/eureka/
      defaultZone: http://eureka:8761/eureka/
