version: "3.8"
services:
  eureka:
    image: ghcr.io/<owner>/eureka-server:${IMAGE_TAG}
    container_name: eureka
    ports: ["8761:8761"]
    restart: unless-stopped

  api-gateway:
    image: ghcr.io/<owner>/api-gateway:${IMAGE_TAG}
    container_name: api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    ports: ["80:8080"]   # 외부는 80
    depends_on: [eureka]
    restart: unless-stopped
