version: "3.8"
services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      - MARIADB_DATABASE=health_tracker
      - MARIADB_USER=health
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    ports: ["3306:3306"]
    restart: unless-stopped

  user-service-1:
    image: ghcr.io/<owner>/user-service:${IMAGE_TAG}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/health_tracker
      - SPRING_DATASOURCE_USERNAME=health
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://<EUREKA_PRIVATE_IP>:8761/eureka/
    expose: ["8081"]
    depends_on: [mariadb]
    restart: unless-stopped

  user-service-2:
    image: ghcr.io/<owner>/user-service:${IMAGE_TAG}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/health_tracker
      - SPRING_DATASOURCE_USERNAME=health
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://<EUREKA_PRIVATE_IP>:8761/eureka/
    expose: ["8081"]
    depends_on: [mariadb]
    restart: unless-stopped

  routine-service-1:
    image: ghcr.io/<owner>/routine-service:${IMAGE_TAG}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/health_tracker
      - SPRING_DATASOURCE_USERNAME=health
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://<EUREKA_PRIVATE_IP>:8761/eureka/
    expose: ["8082"]
    depends_on: [mariadb]
    restart: unless-stopped

  nginx-cache:
    image: nginx:1.27
    container_name: nginx-cache
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cache:/var/cache/nginx
    ports: ["9000:9000"]
    depends_on: [user-service-1, user-service-2, routine-service-1]
    restart: unless-stopped
