server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://<MARIADB_PRIVATE_IP>:3306/health_routine?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=UTC
    username: health
    password: <비번>
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # ✅ Flyway를 routine-service에서 돌리므로 여기선 validate 권장
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: false   # ✅ user-service에서는 Flyway 아예 끄기
eureka:
  client:
    service-url:
      defaultZone: http://<EUREKA_PRIVATE_IP>:8761/eureka/
management.endpoints.web.exposure.include: "*"
security:
  api-key: ${API_KEY:SECRET_MINIPROJECT}  # 환경변수 없으면 기본값 SECRET_MINIPROJECT
